# Generated by Django 2.0.4 on 2018-07-18 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20180718_1144'),
        ('parametric', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametric',
            name='name',
        ),
        migrations.AddField(
            model_name='parametric',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
    ]
