# Generated by Django 2.0.4 on 2018-07-18 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametric', '0002_auto_20180718_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametric',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametrics', to='item.Item'),
        ),
    ]
