# Generated by Django 2.0.4 on 2018-10-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serialnumber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='serialnumber.SerialNumber'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='unit_type',
            field=models.CharField(choices=[('BUILT', 'Built'), ('COMPONENT', 'Component')], default='BUILT', max_length=10),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='wip',
            field=models.BooleanField(default=True, verbose_name='Still In Process'),
        ),
    ]
