rmdir bom\migrations /s/q
rmdir defect_code\migrations /s/q
rmdir failure\migrations /s/q
rmdir freeze\migrations /s/q
rmdir hook\migrations /s/q
rmdir item\migrations /s/q
rmdir operation\migrations /s/q
rmdir parameter\migrations /s/q
rmdir parametric\migrations /s/q
rmdir performing\migrations /s/q
rmdir product\migrations /s/q
rmdir routing\migrations /s/q
rmdir serialnumber\migrations /s/q
rmdir snippet\migrations /s/q
rmdir symptom\migrations /s/q
rmdir symptom_code\migrations /s/q
rmdir user_profile\migrations /s/q
rmdir workorder\migrations /s/q