# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd', models.CharField(max_length=50, verbose_name='Ref Destinator')),
                ('pn', models.CharField(max_length=50, verbose_name='Part Number')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('category1', models.CharField(blank=True, max_length=50, null=True)),
                ('category2', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_pn', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_pn', models.IntegerField(default=0, verbose_name='Alternative Part')),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.Bom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bomdetail',
            unique_together=set([('rd', 'pn', 'bom', 'alt_pn')]),
        ),
    ]
