# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BomDetail',
            new_name='Bom_Detail',
        ),
    ]
