# Generated by Django 2.0.4 on 2018-10-25 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('symptom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('performing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performing.Performing')),
                ('symptomcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom.SymptomCode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
