# Generated by Django 2.0.4 on 2018-10-27 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0002_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='performing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='performing.Performing'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptomcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='symptom.SymptomCode'),
        ),
    ]
