# Generated by Django 2.0.4 on 2018-12-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0003_auto_20181027_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='remark',
            new_name='note',
        ),
    ]
