# Generated by Django 2.0.4 on 2018-12-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0005_symptom_ndf'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomcode',
            name='defect_type',
            field=models.CharField(choices=[('VISUAL', 'Visual Inspection'), ('FUNCTIONAL', 'Functional Test')], default='VISUAL', max_length=20),
        ),
    ]
