# Generated by Django 2.0.4 on 2018-12-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0006_symptomcode_defect_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptomcode',
            old_name='defect_type',
            new_name='symptom_type',
        ),
    ]
