# Generated by Django 2.0.4 on 2018-12-18 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0008_auto_20181218_1518'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndf', models.BooleanField(default=False, verbose_name='No Defect Found')),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('defectcodecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='defect.DefectCode')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='symptom.Symptom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
